# Nome da aplicação (informativo)
spring.application.name=classwatch-backend

# Banco H2 em memória (apaga tudo ao reiniciar)
spring.datasource.url=jdbc:h2:mem:testdb

# Driver do H2
spring.datasource.driverClassName=org.h2.Driver

# Usuário padrão
spring.datasource.username=sa

# Senha vazia (padrão H2)
spring.datasource.password=

# Dialeto do Hibernate (fala "SQL do H2")
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Atualiza automaticamente as tabelas com base nas entidades
spring.jpa.hibernate.ddl-auto=update

# Ativa console web do H2
spring.h2.console.enabled=true

# URL para acessar o console
spring.h2.console.path=/h2-console

python.path=C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python313\\python.exe
script.path=C:\\Users\\Usuario\\Documents\\Projetos\\classwatch\\ai\\transcricao.py