# Nome da aplicação (informativo)
spring.application.name=classwatch-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/classwatch
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


python.path=C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python313\\python.exe
script.path=C:\\Users\\Usuario\\Documents\\Projetos\\classwatch\\ai\\transcricao.py

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB